# ==============================================================================
# Copyright (C) 2024, Griffin Downs. All rights reserved.
# This file is part of cto-assets-rtis. See LICENSE.md for details.
# ==============================================================================


name: Build Project Artifact

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        choco install --yes ninja
      shell: pwsh

    - name: Run the build script
      run: .\Build-Project.ps1
      shell: pwsh

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: cto-assets-rtis
        path: build/bin/*
